version: "3.9"
services:
  servVenda:
    ports:
      - "8081:8080"
    image: "venda:latest"
  msVenda:
    ports:
      - "8082:8080"
    image: "msvendas:latest"
  msEstoque:
    ports:
      - "8086:8080"
    image: "msestoque:latest" 
  gateway:
    ports:
      - "8080:8080"
    image: "gateway:latest"
 